"""
Standards divergence mapping: PEDO Checklist for Accessibility Audit
vs Accessibility Code of Pakistan 2006.

Single source of truth. Emits:
  - standards_mapping.csv   (human review / spreadsheet)
  - requirements_seed.json  (seeds the `requirement` table)
  - mapping_table.tex       (Appendix B longtable)

VERDICT values
  CODE_STRICTER      Code threshold is more demanding than checklist
  CHECKLIST_STRICTER Checklist threshold is more demanding than Code
  CONFLICT           Ranges do not overlap, or scoping methods differ materially
  MATCH              Equivalent
  GAP_CHECKLIST      Code requires something the checklist never asks
  GAP_CODE           Checklist asks something the Code does not specify

AUTHORITY values
  BINDING    stated in the Accessibility Code of Pakistan 2006
  ADVISORY   expected in the Design Manual 2006 (non-binding) - to confirm
  UNSOURCED  checklist-only; no Pakistani source located

APPLIES
  ALL | NEW | EXISTING | EXTERIOR | INTERIOR
"""

ROWS = [
    # key, topic, checklist_items, checklist_value, code_ref, code_value,
    # authority, applies, verdict, applied, note

    # ---------------- Routes and circulation ----------------
    dict(key="route.width.exterior", topic="Accessible route",
         cl="3.2", clv="36 in min", ref="5.2.1(iii)", cv="48 in min",
         auth="BINDING", app="EXTERIOR", verdict="CODE_STRICTER", applied="48 in",
         note="Code also requires handrail protection where level drop from adjoining ground exceeds 18 in."),
    dict(key="route.width.interior", topic="Accessible route",
         cl="9.3", clv="36 in min, may narrow to 32 in for max 24 in", ref="6.2.1(ii)", cv="48 in min except at doors",
         auth="BINDING", app="INTERIOR", verdict="CODE_STRICTER", applied="48 in",
         note="Checklist narrowing allowance has no Code equivalent."),
    dict(key="route.passing.space", topic="Accessible route",
         cl="9.3", clv="narrow portions 48 in apart", ref="6.2.1(iii)", cv="if width < 60 in, provide 60 x 60 in passing spaces at intervals not exceeding 100 ft",
         auth="BINDING", app="INTERIOR", verdict="CONFLICT", applied="Code",
         note="Different mechanism entirely. Corridor intersection counts as passing space."),
    dict(key="route.headroom", topic="Accessible route",
         cl="11.78", clv="6 ft 6 in (78 in)", ref="6.2.1(v)", cv="80 in min",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="80 in",
         note="Checklist value appears under landscape planting; Code sets it for the whole accessible route."),
    dict(key="route.level.gradient", topic="Accessible route",
         cl="3.3, 9.4", clv="running slope not steeper than 1:20", ref="5.2.1(ii)", cv="gradient less than 1:20 is level access",
         auth="BINDING", app="ALL", verdict="MATCH", applied="1:20",
         note=""),
    dict(key="route.surface", topic="Accessible route",
         cl="3.1, 9.2", clv="stable, firm, slip-resistant", ref="5.2.5(i), 6.2.2(iii)", cv="firm, slip-resistant, reasonably smooth, especially under wet conditions",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code names wet conditions explicitly."),
    dict(key="route.tactile", topic="Accessible route",
         cl="1.3", clv="tactile blocks in sidewalk and crossing", ref="5.2.5(ii)", cv="detectable tactile surface across full width at each level change and at head and foot of ramps and steps",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code is more specific about placement."),
    dict(key="route.egress.link", topic="Accessible route",
         cl="-", clv="not asked", ref="6.2.1(vi)", cv="a sole accessible route must also serve as means of emergency egress or connect to an area of refuge",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="New item required."),

    # ---------------- Walkways / crossings ----------------
    dict(key="walkway.width", topic="Walkways",
         cl="3.2", clv="36 in", ref="5.2.7(i)", cv="48 in min; 36 in clear at identified obstructions",
         auth="BINDING", app="EXTERIOR", verdict="CODE_STRICTER", applied="48 in / 36 in at obstruction",
         note=""),
    dict(key="walkway.gradient", topic="Walkways",
         cl="-", clv="not asked", ref="5.2.7(ii)", cv="should not exceed 1:12",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="1:12",
         note=""),
    dict(key="walkway.gratings", topic="Walkways",
         cl="-", clv="not asked", ref="5.2.7(iv)", cv="no parallel bars; apertures at right angles to travel, not larger than 1 in wide",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="1 in",
         note="New item required."),
    dict(key="crossing.curbramp", topic="Pedestrian crossings",
         cl="4.1, 11.49, 11.52", clv="curb ramp where route crosses curb; level differences over 19 mm", ref="5.2.8(i), 5.2.7(iii)", cv="all marked crossings shall have curb ramps and detectable floor paving",
         auth="BINDING", app="EXTERIOR", verdict="CODE_STRICTER", applied="Code",
         note="Checklist 11.49 uses 19 mm, the only metric value in an otherwise imperial document; no Code basis found."),
    dict(key="crossing.signals", topic="Pedestrian crossings",
         cl="11.48, 11.51", clv="audible and flashing crossing signals", ref="5.2.8(iii)", cv="auditory signals and manually operated traffic lights where possible in high pedestrian traffic areas",
         auth="BINDING", app="EXTERIOR", verdict="CONFLICT", applied="Code",
         note="Checklist states it as a requirement; Code phrases it as 'where possible'. Downgrade severity."),
    dict(key="crossing.width", topic="Pedestrian crossings",
         cl="11.50", clv="at least 10 ft wide, 4 in white lines", ref="-", cv="not specified",
         auth="UNSOURCED", app="EXTERIOR", verdict="GAP_CODE", applied="checklist, flagged",
         note="No Code basis. Check Design Manual before citing."),

    # ---------------- Ramps ----------------
    dict(key="ramp.slope.new", topic="Ramps",
         cl="6.3, 9.16", clv="1:12 max; 1:8 for rise <= 3 in, 1:10 for rise <= 6 in where space limited", ref="5.2.3(i)", cv="should not exceed 1:20; shall not exceed 1:12 for new construction",
         auth="BINDING", app="NEW", verdict="CONFLICT", applied="1:12",
         note="Code gives no space-limitation exception for new build. Checklist exceptions are ADA-derived."),
    dict(key="ramp.slope.existing", topic="Ramps",
         cl="-", clv="not distinguished", ref="5.2.3(ii)", cv="up to 1:8 permitted for existing development ONLY where an alternative stepped approach is also provided",
         auth="BINDING", app="EXISTING", verdict="GAP_CHECKLIST", applied="1:8 conditional",
         note="Requires new-vs-existing site attribute and a conditional threshold."),
    dict(key="ramp.crossslope", topic="Ramps",
         cl="8.2", clv="1:48 (door manoeuvring)", ref="5.2.3(iii)", cv="1:50 max",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="1:50",
         note="Minor numeric difference; adopt Code."),
    dict(key="ramp.width.exterior", topic="Ramps",
         cl="6.1", clv="36 in min", ref="5.2.3(iv)", cv="48 in min",
         auth="BINDING", app="EXTERIOR", verdict="CODE_STRICTER", applied="48 in",
         note=""),
    dict(key="ramp.width.interior", topic="Ramps",
         cl="9.14", clv="36 in min", ref="6.2.3(v)", cv="36 in min with passing space at landings",
         auth="BINDING", app="INTERIOR", verdict="MATCH", applied="36 in",
         note="Exterior and interior differ in the Code; the checklist uses one value for both."),
    dict(key="ramp.rise.max", topic="Ramps",
         cl="-", clv="not asked", ref="5.2.3(v)", cv="max rise between two landings 30 in",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="30 in",
         note="New item required."),
    dict(key="ramp.run.max", topic="Ramps",
         cl="-", clv="not asked", ref="6.2.3(iv)", cv="single run shall not exceed 48 ft",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="48 ft",
         note="New item required."),
    dict(key="ramp.landing", topic="Ramps",
         cl="6.4, 6.5, 9.17, 9.18", clv="60 in long, ramp width; 60 x 60 in at direction change", ref="6.2.3(v)", cv="passing space provided at landings (undimensioned)",
         auth="BINDING", app="ALL", verdict="GAP_CODE", applied="checklist, flagged",
         note="Code does not dimension landings. Check Design Manual."),
    dict(key="ramp.handrail.trigger", topic="Ramps",
         cl="6.6, 9.19", clv="handrails both sides if rise > 6 in", ref="7.7.1", cv="handrails required unless gradient is less than 1:20",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code",
         note="Different trigger: rise-based vs gradient-based."),
    dict(key="ramp.balustrade", topic="Ramps",
         cl="-", clv="not asked", ref="7.7.2", cv="balustrade required where drop to the side exceeds 18 in",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="18 in",
         note="New item required."),

    # ---------------- Stairs ----------------
    dict(key="stair.riser.exterior", topic="Stairs",
         cl="5.1", clv="not more than 6.5 in", ref="5.2.4(ii)", cv="not more than 6 in",
         auth="BINDING", app="EXTERIOR", verdict="CODE_STRICTER", applied="6 in",
         note=""),
    dict(key="stair.riser.interior", topic="Stairs",
         cl="9.6", clv="not more than 6.5 in", ref="6.2.3(iii)", cv="max riser 7 in",
         auth="BINDING", app="INTERIOR", verdict="CHECKLIST_STRICTER", applied="6.5 in, flagged",
         note="Three different values across the two documents. Resolve with consultant."),
    dict(key="stair.tread", topic="Stairs",
         cl="5.1, 9.6", clv="not less than 11 in", ref="5.2.4(ii), 6.2.3(iii)", cv="not less than 11 in",
         auth="BINDING", app="ALL", verdict="MATCH", applied="11 in",
         note="Code 6.2.3(iii) says 'head width', read as tread."),
    dict(key="stair.width.exterior", topic="Stairs",
         cl="5.2", clv="asked, no threshold given", ref="5.2.4(i)", cv="not less than 36 in",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="36 in",
         note="Checklist records the measurement but sets no pass criterion."),
    dict(key="stair.width.interior", topic="Stairs",
         cl="9.7", clv="asked, no threshold given", ref="6.2.3(ii)", cv="min 42 in clear between handrails (low-rise buildings)",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="42 in",
         note=""),
    dict(key="stair.single.step", topic="Stairs",
         cl="-", clv="not asked", ref="5.2.4(iii)", cv="single steps should be avoided",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="advisory",
         note="'Should' - preferred standard, not mandatory."),

    # ---------------- Handrails ----------------
    dict(key="handrail.height.exterior", topic="Handrails",
         cl="5.4", clv="34 to 38 in", ref="5.2.6(iii)", cv="not less than 30 in, not more than 42 in",
         auth="BINDING", app="EXTERIOR", verdict="CONFLICT", applied="30 to 42 in",
         note="Checklist range sits inside Code range; a 32 in rail passes Code, fails checklist."),
    dict(key="handrail.height.general", topic="Handrails",
         cl="6.7, 9.9, 9.20", clv="34 to 38 in", ref="7.7.3", cv="not less than 30 in, not more than 48 in",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="30 to 48 in",
         note="Code is markedly wider. Adopt Code; note the divergence in the report."),
    dict(key="handrail.diameter", topic="Handrails",
         cl="5.5, 6.8, 9.10, 9.21", clv="circular 1.25 to 2 in dia", ref="5.2.6(ii), 7.7.4", cv="circular or oval, max 2 in dia at grip; no lower bound",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="max 2 in",
         note="Code sets no minimum. Retain checklist minimum as advisory."),
    dict(key="handrail.noncircular", topic="Handrails",
         cl="5.6, 6.9, 9.11, 9.22", clv="perimeter 4 to 6.25 in", ref="7.7.4", cv="circular or oval only",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code",
         note="Code effectively disallows non-circular profiles; checklist dimensions them."),
    dict(key="handrail.extension", topic="Handrails",
         cl="5.3, 9.8", clv="extend 12 in beyond top and bottom", ref="5.2.6(ii), 6.2.3(vii), 7.7.4", cv="extend min 12 in beyond step or ramp, horizontally, at each end",
         auth="BINDING", app="ALL", verdict="MATCH", applied="12 in",
         note=""),
    dict(key="handrail.wall.clearance", topic="Handrails",
         cl="12.27, 12.28", clv="1.5 in space to wall (grab bars)", ref="7.7.4", cv="fixed min 1.5 in from wall surface",
         auth="BINDING", app="ALL", verdict="MATCH", applied="1.5 in",
         note=""),
    dict(key="handrail.parallel.spacing", topic="Handrails",
         cl="-", clv="not asked", ref="6.2.3(vi), 7.7.5", cv="max 72 in between parallel handrails",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="72 in",
         note="New item required."),
    dict(key="handrail.both.sides", topic="Handrails",
         cl="5.3, 9.8", clv="continuous rails both sides", ref="5.2.4(iv), 6.2.3(vi)", cv="outdoor: at least one side. Accessible stair/ramp: both sides",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="both sides interior, one side min exterior",
         note="Code is weaker outdoors."),
    dict(key="handrail.ends", topic="Handrails",
         cl="-", clv="not asked", ref="7.7.4", cv="ends shall be rounded and not become hazardous as protruding objects",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note=""),

    # ---------------- Parking ----------------
    dict(key="parking.count.car", topic="Parking",
         cl="2.1", clv="1-25:1, 26-50:2, 51-75:3, 76-100:4", ref="5.2.9(ii),(iii)", cv="under 20 spaces: none required. 20-50: at least 1. Over 50: min 2 percent",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code",
         note="Materially different. At 100 spaces: checklist 4, Code 2. Below 20 spaces the Code requires none."),
    dict(key="parking.width.car", topic="Parking",
         cl="2.5", clv="8 ft space + 5 ft aisle", ref="5.2.10(i)", cv="not less than 12 ft total, inclusive of a 48 in access aisle",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="12 ft incl. 48 in aisle",
         note="Checklist totals 13 ft; Code totals 12 ft with a narrower aisle."),
    dict(key="parking.aisle.shared", topic="Parking",
         cl="2.5", clv="two spaces may share an aisle", ref="5.2.10(ii)", cv="a 48 in aisle may be shared between two adjacent spaces",
         auth="BINDING", app="ALL", verdict="MATCH", applied="shared permitted",
         note=""),
    dict(key="parking.van", topic="Parking",
         cl="2.3, 2.4", clv="1 van space per 6; 11 ft + 5 ft aisle, or 8 ft + 8 ft", ref="-", cv="not specified",
         auth="UNSOURCED", app="ALL", verdict="GAP_CODE", applied="drop or mark advisory",
         note="Van-accessible space is an ADA concept with no Code equivalent."),
    dict(key="parking.motorcycle", topic="Parking",
         cl="2.2", clv="scooter space 4 x 5 ft, 3 ft gap", ref="5.2.9(iv),(v), 5.2.10(iii)", cv="50+ combined m/cycle and cycle spaces: 1 reserved. Over 50: min 4 percent. Width not less than 6 ft",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code",
         note="Code has scoping and a wider space; checklist has different dimensions and no scoping."),
    dict(key="parking.headroom", topic="Parking",
         cl="-", clv="not asked", ref="5.2.10(iv)", cv="indoor accessible parking min height clearance 8 ft",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="8 ft",
         note="New item required."),
    dict(key="parking.location", topic="Parking",
         cl="2.6", clv="access aisles adjoin an accessible route", ref="5.2.9(vi)", cv="reserved spaces located in clear view of and nearest to the accessible entrance",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code adds proximity and visibility, not just connectivity."),
    dict(key="parking.multistorey", topic="Parking",
         cl="-", clv="not asked", ref="5.2.9(i)", cv="at least one floor of a multi-storey indoor parking facility served by accessible lift or ramp",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note=""),
    dict(key="parking.marking", topic="Parking",
         cl="2.7", clv="sign with ISA, bottom min 60 in above ground; ground marking not required", ref="5.2.10(v)", cv="clearly identified on the ground surface with internationally accepted markings",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code",
         note="Direct contradiction: checklist says ground marking not required, Code requires it."),

    # ---------------- Doors ----------------
    dict(key="door.width.entrance", topic="Doors",
         cl="8.1", clv="32 in clear at 90 degrees", ref="5.2.2(ii), 6.2.2(i)", cv="not less than 33 in clear, and 80 in high, opening in direction of travel",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="33 in",
         note="Code also sets door height, which the checklist omits."),
    dict(key="door.width.internal", topic="Doors",
         cl="-", clv="not asked separately", ref="7.6.6", cv="33 in when approached at an angle; 30 in when approached straight on",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="33 in / 30 in by approach",
         note="Approach-dependent threshold; needs a conditional."),
    dict(key="door.width.toilet", topic="Doors",
         cl="12.6", clv="32 in clear", ref="7.3.9", cv="at least 30 in clear",
         auth="BINDING", app="ALL", verdict="CHECKLIST_STRICTER", applied="32 in, flagged",
         note=""),
    dict(key="door.threshold", topic="Doors",
         cl="8.3, 12.8", clv="0.25 in max if vertical", ref="6.2.2(iii)", cv="level change at threshold shall not exceed 0.75 in",
         auth="BINDING", app="ALL", verdict="CHECKLIST_STRICTER", applied="0.75 in",
         note="Threefold difference. Adopt Code as the pass threshold; note checklist value as preferred."),
    dict(key="door.handle.height", topic="Doors",
         cl="8.4, 12.10", clv="34 to 48 in", ref="7.6.7", cv="not less than 38 in, not more than 42 in; lever-type handles",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="38 to 42 in",
         note="Code is much narrower and mandates lever handles explicitly."),
    dict(key="door.handle.clearance", topic="Doors",
         cl="8.2, 12.7", clv="18 in beyond latch side plus 60 in clear depth", ref="7.6.2", cv="unobstructed space min 12 in adjacent to door handle on leading face",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code, checklist advisory",
         note="Different measurement basis."),
    dict(key="door.force", topic="Doors",
         cl="8.6, 12.11", clv="5 lbf max", ref="-", cv="not specified",
         auth="UNSOURCED", app="ALL", verdict="GAP_CODE", applied="checklist, flagged",
         note="No Code basis. Requires a pressure gauge; consider dropping from MVP."),
    dict(key="door.swing.toilet", topic="Doors",
         cl="12.34", clv="compartment area beyond swing", ref="7.6.3", cv="toilet doors to accessible compartments shall invariably open out",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code mandates outward swing; checklist only dimensions the inward case."),
    dict(key="door.kickplate", topic="Doors",
         cl="-", clv="not asked", ref="7.6.8", cv="kick plates not less than 10 in high",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="10 in",
         note="New item required."),
    dict(key="door.revolving", topic="Doors",
         cl="-", clv="not asked", ref="7.6.5", cv="revolving doors shall not be considered accessible; automatic swing doors shall not open against direction of travel",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="New item required."),
    dict(key="door.glass", topic="Doors",
         cl="-", clv="not asked", ref="7.6.9", cv="frameless glass doors avoided unless prominently marked",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note=""),

    # ---------------- Space allowance ----------------
    dict(key="space.wheelchair.stationary", topic="Space allowance",
         cl="10.1, 11.6, 12.19", clv="30 x 48 in clear floor space", ref="7.2.1", cv="36 x 48 in for stationary wheelchair; 48 x 48 in for both forward and side approach",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="36 x 48 in",
         note="Checklist uses the ADA 30 in figure throughout."),
    dict(key="space.turning", topic="Space allowance",
         cl="11.8, 11.15, 11.17, 12.16", clv="60 in circle or T-shape in 60 in square", ref="7.2.1", cv="60 in diameter circle",
         auth="BINDING", app="ALL", verdict="MATCH", applied="60 in circle",
         note="Code does not mention the T-shaped alternative."),
    dict(key="space.forward.reach", topic="Space allowance",
         cl="10.1", clv="operable parts no higher than 48 in", ref="7.2.2", cv="forward reach 16 in min to 48 in max; over an obstruction max 20 in; side reach 10 to 52 in",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code sets a lower bound the checklist omits."),
    dict(key="space.cane.zone", topic="Space allowance",
         cl="9.5", clv="protrusions max 4 in; leading edge 27 in or lower, or 80 in or higher", ref="7.2.2", cv="white cane zone extends 48 in across and 28 in in height",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="Code 28 in",
         note="27 in vs 28 in detection height."),

    # ---------------- Toilets ----------------
    dict(key="toilet.provision", topic="Sanitary facilities",
         cl="12.1", clv="at least one accessible toilet, per sex or unisex", ref="7.3.1", cv="at every floor where toilets are provided, at least one accessible toilet for male and female",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code requires this per floor, not per building."),
    dict(key="toilet.clear.space", topic="Sanitary facilities",
         cl="12.16", clv="60 in turning circle", ref="7.3.2", cv="at least 60 in wide clear space in both directions; smaller toilets shall have door opening outside",
         auth="BINDING", app="ALL", verdict="MATCH", applied="60 in",
         note=""),
    dict(key="wc.seat.height", topic="Sanitary facilities",
         cl="12.26", clv="17 to 19 in to top of seat", ref="7.3.4", cv="18 to 20 in above floor level",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="18 to 20 in",
         note="Ranges overlap only between 18 and 19 in."),
    dict(key="wc.centreline", topic="Sanitary facilities",
         cl="12.24", clv="16 to 18 in from side wall", ref="7.3.4", cv="18 to 21 in from centre line to adjoining wall",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="18 to 21 in",
         note="RANGES BARELY OVERLAP. A 17 in installation passes the checklist and fails the Code. Highest-priority resolution."),
    dict(key="wc.type", topic="Sanitary facilities",
         cl="12.23", clv="is the facility commode (yes/no)", ref="7.3.4", cv="European type water closet; back support if un-coupled",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code adds the back-support requirement."),
    dict(key="wc.muslim.shower", topic="Sanitary facilities",
         cl="-", clv="not asked", ref="7.3.5", cv="reachable Muslim shower shall be provided at the adjoining wall",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Locally significant requirement entirely absent from the ADA-derived checklist."),
    dict(key="grab.bar.length", topic="Sanitary facilities",
         cl="12.27, 12.28", clv="42 in side wall, 36 in rear wall", ref="7.7.6", cv="not less than 24 in",
         auth="BINDING", app="ALL", verdict="CHECKLIST_STRICTER", applied="checklist, flagged",
         note="Code sets a much lower floor. Retaining the checklist value is defensible but must be disclosed."),
    dict(key="grab.bar.projection", topic="Sanitary facilities",
         cl="12.27, 12.28", clv="1.5 in space between wall and bar", ref="7.7.6", cv="shall extend 2 in away from the wall",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="2 in",
         note=""),
    dict(key="grab.bar.diameter", topic="Sanitary facilities",
         cl="-", clv="not asked", ref="7.7.6", cv="external diameter between 1 and 2 in; plastic covered preferred over chrome; slightly corrugated surface recommended",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="1 to 2 in",
         note="New item required."),
    dict(key="mirror.height", topic="Sanitary facilities",
         cl="12.18", clv="bottom edge max 40 in", ref="7.3.7", cv="bottom of mirror not more than 40 in above floor level",
         auth="BINDING", app="ALL", verdict="MATCH", applied="40 in",
         note=""),
    dict(key="toilet.controls.height", topic="Sanitary facilities",
         cl="12.29", clv="flush control max 48 in", ref="7.3.7", cv="all operable parts and controls of fixtures within 40 to 48 in above floor level",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="40 to 48 in",
         note="Code sets a lower bound."),
    dict(key="basin.type", topic="Sanitary facilities",
         cl="12.20, 12.21", clv="front max 34 in; 27 in knee clearance, 8 in deep", ref="7.3.3", cv="wall mounted with lever handle controls; insulated and concealed hot water pipes",
         auth="BINDING", app="ALL", verdict="GAP_CODE", applied="both",
         note="Code specifies type and safety, checklist specifies geometry. Merge; neither supersedes the other."),
    dict(key="toilet.door.pullbar", topic="Sanitary facilities",
         cl="-", clv="not asked", ref="7.3.9", cv="24 in pull bar on inside; lockable inside, releasable from outside in emergency; spring or gravity closing hinges",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="New item required; the emergency-release provision is a safety requirement."),
    dict(key="shower.area", topic="Sanitary facilities",
         cl="-", clv="not asked", ref="7.3.6", cv="clear dimension 48 x 48 in; horizontal grab bar and folding waterproof shower seat preferred",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="48 x 48 in",
         note=""),

    # ---------------- Lifts ----------------
    dict(key="lift.provision", topic="Lifts",
         cl="9.23", clv="elevators or platform lifts to all public storeys", ref="6.2.3(i) [second]", cv="in all multi-storey buildings at least one accessible lift serving all accessible floors",
         auth="BINDING", app="INTERIOR", verdict="MATCH", applied="Code",
         note=""),
    dict(key="lift.door.width", topic="Lifts",
         cl="9.26, 9.27", clv="32 in min (full size), 36 in (LULA variant)", ref="7.8.1", cv="min clear width 30 in; sliding or outward opening",
         auth="BINDING", app="INTERIOR", verdict="CHECKLIST_STRICTER", applied="32 in, flagged",
         note="LULA is an ADA category with no Code equivalent."),
    dict(key="lift.controls.height", topic="Lifts",
         cl="9.28", clv="15 to 42 in, or up to 48 in for parallel approach", ref="7.8.1", cv="switches and controls not more than 48 in above floor level",
         auth="BINDING", app="INTERIOR", verdict="MATCH", applied="Code max 48 in",
         note="Code sets no lower bound; retain 15 in as advisory."),
    dict(key="lift.braille", topic="Lifts",
         cl="9.29", clv="raised characters and Braille on car controls", ref="7.8.1, 7.8.4", cv="talking and Braille signs in addition to regular signs",
         auth="BINDING", app="INTERIOR", verdict="CODE_STRICTER", applied="Code",
         note="Code requires audible announcement, not merely tactile marking."),
    dict(key="lift.size", topic="Lifts",
         cl="9.26", clv="54 in deep x 36 in wide, 16 sq ft min", ref="7.8.3", cv="size such that it accommodates at least one wheelchair user with an attendant (undimensioned)",
         auth="BINDING", app="INTERIOR", verdict="GAP_CODE", applied="checklist, flagged",
         note="Code is qualitative. Check Design Manual for the dimension."),
    dict(key="lift.floor", topic="Lifts",
         cl="-", clv="not asked", ref="7.8.2", cv="cab floor slip-resistant; walls resistant to wheelchair damage",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note=""),
    dict(key="lift.freight", topic="Lifts",
         cl="-", clv="not asked", ref="7.8.6", cv="a freight elevator shall not be considered an accessible lift",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note="Disqualifying condition; affects NA logic."),

    # ---------------- Controls, signage, illumination ----------------
    dict(key="controls.height", topic="Controls",
         cl="10.1", clv="operable parts no higher than 48 in", ref="7.9.1", cv="recommended height 42 in above floor level",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="max 48 in, 42 in preferred",
         note="Code phrases 42 in as a recommendation, not a limit."),
    dict(key="controls.pullknob", topic="Controls",
         cl="-", clv="not asked", ref="7.9.2", cv="pull knobs for ceiling switches not more than 40 in above floor",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="40 in",
         note=""),
    dict(key="signage.character.height", topic="Signage",
         cl="-", clv="not asked", ref="6.2.6(ii)", cv="minimum character height 3 in for accessibility signage",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="3 in",
         note="Significant gap. Checklist covers Braille placement but never character size."),
    dict(key="signage.braille.height", topic="Signage",
         cl="Ch.1", clv="Braille and tactile between 900 and 1500 mm, ideal 1050 mm", ref="5.2.12(ii)", cv="directional and guidance signs supplemented with Braille where within reach",
         auth="BINDING", app="ALL", verdict="GAP_CODE", applied="checklist, flagged",
         note="Checklist Chapter 1 is the only metric section in the document; no Code basis for the figures."),
    dict(key="signage.illuminated", topic="Signage",
         cl="-", clv="not asked", ref="5.2.12(i), 6.2.6(iii)", cv="signs shall be illuminated internally or externally",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="New item required."),
    dict(key="illumination.general", topic="Illumination",
         cl="-", clv="15.4 asks 'adequate and without glare', unquantified", ref="5.2.11, 6.2.3(ii),(iii)", cv="min 5 foot-candle (55 lux) at all times; general illumination preferably 10 to 20 foot-candle (110 to 220 lux)",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="55 lux min",
         note="Requires a light meter in the tool kit. Significant addition to the instrument."),
    dict(key="illumination.backup", topic="Illumination",
         cl="-", clv="not asked", ref="6.2.3(iv)", cv="on power failure, illumination maintained by emergency supply for the duration the space is occupied",
         auth="BINDING", app="INTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note=""),

    # ---------------- Assembly and seating ----------------
    dict(key="assembly.wheelchair.count", topic="Assembly seating",
         cl="11.40", clv="table 4-25:1, 26-50:2, 51-150:4, 151-300:5, with a note stating 5 percent", ref="7.5.1", cv="2 percent of seats reserved for wheelchair users",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="2 percent",
         note="Checklist is internally inconsistent: its note says 5 percent, its table yields roughly 2.7 to 8 percent."),
    dict(key="assembly.paired", topic="Assembly seating",
         cl="-", clv="not asked", ref="7.5.2", cv="designated wheelchair spaces should where possible be paired",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="advisory",
         note=""),
    dict(key="assembly.clear.space", topic="Assembly seating",
         cl="11.43, 11.44, 11.45", clv="36 in wide; 48 in deep front/rear entry; 60 in side entry", ref="7.5.5", cv="36 in wide clear space in front of first row or behind last row",
         auth="BINDING", app="ALL", verdict="GAP_CODE", applied="both",
         note="Different aspects; merge rather than choose."),
    dict(key="assembly.stage", topic="Assembly seating",
         cl="11.39", clv="ramp to stage/podium if provided", ref="7.5.7", cv="the stage or activity area shall be accessible",
         auth="BINDING", app="ALL", verdict="MATCH", applied="Code",
         note=""),
    dict(key="seating.dining.count", topic="Seating",
         cl="11.3", clv="at least 5 percent, no fewer than one", ref="-", cv="not specified",
         auth="UNSOURCED", app="ALL", verdict="GAP_CODE", applied="checklist, flagged",
         note="No Code basis for dining seating percentage."),
    dict(key="counter.height", topic="Counters",
         cl="11.5, 11.36", clv="28 to 34 in dining; max 36 in service counter", ref="7.4.2", cv="counter tops 30 to 33 in high; depth not more than 21 in; clear knee space underneath",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="30 to 33 in",
         note="Code range is narrower and adds a depth limit."),
    dict(key="shelving.height", topic="Counters",
         cl="11.29, 11.30, 11.38", clv="displays max 36 in; overhead shelves above 49 in; dispensers max 48 in", ref="7.4.4", cv="shelves and storage between 12 and 48 in above floor level",
         auth="BINDING", app="ALL", verdict="CONFLICT", applied="12 to 48 in",
         note="Code sets a lower bound the checklist lacks."),
    dict(key="hotwater.insulation", topic="Counters",
         cl="-", clv="not asked", ref="7.4.5, 7.3.3", cv="all exposed hot water pipes under sinks and counters shall be insulated and concealed",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Safety requirement absent from the checklist."),

    # ---------------- Egress ----------------
    dict(key="egress.count", topic="Emergency egress",
         cl="14.1, 14.2", clv="exits identifiable and accessible (qualitative)", ref="8.2.2(ii)", cv="one accessible egress per 5,000 sq ft gross floor area, or occupant load of 50, or 100 ft travel distance, whichever is most stringent",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Major gap. Checklist has four qualitative questions where the Code has a computation."),
    dict(key="egress.lift", topic="Emergency egress",
         cl="14.3", clv="is the lift an evacuation lift", ref="8.2.3(iii), 7.8.5", cv="fire-protected construction; operable on emergency power for at least 30 minutes; egress signage; illuminated",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Checklist asks yes/no; Code gives four testable criteria."),
    dict(key="egress.illumination", topic="Emergency egress",
         cl="-", clv="not asked", ref="8.2.4", cv="at least 1 foot-candle (11 lux) at floor level; on failure, emergency supply for 30 min at min 0.1 foot-candle (1 lux)",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note=""),
    dict(key="egress.alarm", topic="Emergency egress",
         cl="13.1", clv="alarms have flashing lights and audible signals", ref="8.2.6", cv="auditory and visual signals covering the entire accessible space",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Code adds full coverage."),
    dict(key="egress.refuge", topic="Emergency egress",
         cl="-", clv="not asked", ref="8.3.1", cv="area of refuge required in all multi-storey buildings and low-rise with 5,000 sq ft accessible floor area; must hold two wheelchairs with attendants; communication to managerial station; tactile door handle warnings",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Entire concept absent from the checklist. Multiple new items."),
    dict(key="egress.plan", topic="Emergency egress",
         cl="14.4", clv="is safety drill performed (yes/no)", ref="8.3.2", cv="written rescue assistance plan required; copy to on-site staff and to the government evacuation agency; drill at least once every year",
         auth="BINDING", app="ALL", verdict="CODE_STRICTER", applied="Code",
         note="Checklist has no frequency and does not ask for the plan document."),
    dict(key="egress.hospital.ramp", topic="Emergency egress",
         cl="-", clv="not asked", ref="8.2.7", cv="in hospitals and buildings for persons requiring mobility assistance, an accessible ramp for egress should be considered",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="advisory",
         note="Sector-gated to Health."),

    # ---------------- Scoping and applicability ----------------
    dict(key="scope.exemption.smallprivate", topic="Scoping",
         cl="-", clv="not asked", ref="3.2.4(iii), 4.3.3(xi)(b)", cv="existing privately owned public-use buildings under 2,500 sq ft gross floor area are exempt",
         auth="BINDING", app="EXISTING", verdict="GAP_CHECKLIST", applied="Code",
         note="Gating condition. Requires site ownership type, gross floor area and new/existing attributes."),
    dict(key="scope.government", topic="Scoping",
         cl="-", clv="not asked", ref="3.2.1", cv="all government-owned or government-occupied buildings covered irrespective of size, location or use",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="No exemption path for government buildings."),
    dict(key="scope.mandatory.vs.preferred", topic="Scoping",
         cl="-", clv="all items weighted equally", ref="4.2.2", cv="mandatory requirements (total compliance new, achievable existing) vs preferred standards (voluntary)",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Maps directly onto item severity weighting. Chapter 4.3 assigns mandatory/preferred per building type."),
    dict(key="scope.residential.units", topic="Scoping",
         cl="-", clv="not asked", ref="4.3.3(i),(ii),(iii)", cv="low-rise: 50 percent of ground floor units. Multi-storey: 10 percent of total units. Hotels: 10 percent of guest rooms",
         auth="BINDING", app="ALL", verdict="GAP_CHECKLIST", applied="Code",
         note="Percentage scoping the checklist never asks about."),
    dict(key="scope.existing.achievable", topic="Scoping",
         cl="-", clv="not asked", ref="3.2.3, 4.2.2(a)", cv="existing buildings modified to an achievable extent within economic capacity",
         auth="BINDING", app="EXISTING", verdict="GAP_CHECKLIST", applied="Code",
         note="Softens findings for existing buildings; affects recommendation wording, not the threshold."),

    # ---------------- Street furniture ----------------
    dict(key="furniture.rest.intervals", topic="Street furniture",
         cl="-", clv="not asked", ref="5.2.13(iii)", cv="resting facilities at intervals between 100 m and 200 m, adjacent to but outside the accessible route",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="100 to 200 m",
         note="Metric in an otherwise imperial Code."),
    dict(key="furniture.contrast", topic="Street furniture",
         cl="-", clv="not asked", ref="5.2.13(ii)", cv="textural and colour changes in floor surface to identify street furniture",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note=""),
    dict(key="toilet.public.outdoor", topic="Public toilets",
         cl="-", clv="sector category exists but no items", ref="5.2.14", cv="at least one unisex accessible toilet per public toilet location, with wash basin, European WC, grab bars, running water, workable illumination; large enough for one wheelchair user plus attendant of either gender",
         auth="BINDING", app="EXTERIOR", verdict="GAP_CHECKLIST", applied="Code",
         note="Public Toilet is one of the twelve sectors but the checklist provides no dedicated items."),
]


def verdict_counts():
    from collections import Counter
    return Counter(r["verdict"] for r in ROWS)


if __name__ == "__main__":
    print(f"{len(ROWS)} rows")
    for k, v in sorted(verdict_counts().items(), key=lambda x: -x[1]):
        print(f"  {k:20s} {v}")
